[GLOBAL]
pants_version = "2.23.0"
backend_packages.add = [
  "pants.backend.python",
]

[source]
root_patterns = ["/"]

[python]
enable_resolves = true
resolves = { python-default = "python-default.lock"}
interpreter_constraints = [">=3.12"]
